name: lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Please tell me who you are.
      run: |
          git config --global user.email "15198247+buyoh@users.noreply.github.com"
          git config --global user.name "buyoh (github workflow)"
    # - name: get git submodules
    #   run: |
    #     git submodule init
    #     git submodule update
    - name: install packages
      run: |
        yarn
    - name: lint javascript
      run: |
        yarn lint-fix
        yarn test
    - name: commit phase
      run: |
        if [ `git diff | wc -l` -ne 0 ] ; then
        echo detect diff
        git add .
        git commit -m 'lint-fix by Github Actions'
        fi
    - name: push
      run: |
        git push origin || : 
